/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion_equipo1.RevisionCV;

import entidades.Candidato;
import entidades.Reclutador;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetosnegocio.CandidatoON;
import objetosnegocio.ReclutadorDAO;

/**
 *
 * @author paula
 */
public class AdminNomina extends javax.swing.JFrame {

    /**
     * Creates new form NominaView
     */
    public AdminNomina() {
        initComponents();
        cargarReclutadoresEnTabla();
    }

    public void cargarReclutadoresEnTabla() {
        // Columnas que se mostrarán
        String[] columnas = {"ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Puesto", "Nomina"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ReclutadorDAO controladorReclutador = ReclutadorDAO.getInstance();
        CandidatoON controladorCandidatos = CandidatoON.getInstance();
        List<Reclutador> listaReclutadores = controladorReclutador.obtenerTodos();
        List<Candidato> listaCandidato = controladorCandidatos.obtenerTodos();

        for (Reclutador r : listaReclutadores) {
            Object[] fila = new Object[]{
                r.getId(),
                r.getNombreCompleto(),
                r.getApellidoPaterno(),
                r.getApellidoMaterno(),
                r.getPuesto(),
                r.getNomina()
            };
            modelo.addRow(fila);
        }

        for (Candidato c : listaCandidato) {
            Object[] fila = new Object[]{
                c.getId(),
                c.getNombre(),
                c.getApellidoPaterno(),
                c.getApellidoMaterno(),
                c.getPuesto(),
                c.getNomina()
            };
            modelo.addRow(fila);
        }
        jTablaRegistros.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaRegistros = new javax.swing.JTable();
        jLabelFotoRH = new javax.swing.JLabel();
        jLabel1CRUDRH = new javax.swing.JLabel();
        jButtonAgregarNomina = new javax.swing.JButton();
        jButtonCerrarVentana = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre ", "Apellido Paterno", "Apellido Materno", "Puesto", "Nomina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaRegistros);

        jLabelFotoRH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rhfoto2.png"))); // NOI18N
        jLabelFotoRH.setText("jLabel2");

        jLabel1CRUDRH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1CRUDRH.setText("Administrador de nómina");

        jButtonAgregarNomina.setText("Agregar/Actualizar");
        jButtonAgregarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNominaActionPerformed(evt);
            }
        });

        jButtonCerrarVentana.setBackground(new java.awt.Color(236, 51, 51));
        jButtonCerrarVentana.setText("Cerrar");
        jButtonCerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabelFotoRH, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1CRUDRH, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAgregarNomina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCerrarVentana))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFotoRH, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1CRUDRH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNominaActionPerformed
        // TODO add your handling code here:
//        RegistroRH agregar = new RegistroRH();
//        agregar.setVisible(true);
//        agregar.addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            public void windowClosed(java.awt.event.WindowEvent e) {
//                cargarReclutadoresEnTabla(); // Método que recarga la JTable
//            }
//        });

        int filaSeleccionada = jTablaRegistros.getSelectedRow();
        if (filaSeleccionada != -1) {
            String input = (String) JOptionPane.showInputDialog(
                    null,
                    "Ingresa el valor de la nómina:",
                    "Entrada de nómina",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    null,
                    jTablaRegistros.getValueAt(filaSeleccionada, 5) // Valor predefinido
            );

            if (input != null && !input.trim().isEmpty()) {
                float nomina = Float.parseFloat(input);
                // Aquí puedes usar el valor para setearlo, por ejemplo:

                int confirmacion = JOptionPane.showConfirmDialog(
                        null, //centra en pantalla
                        "¿El monto '" + nomina + "' de la nomina es correcto?", //el mensaje que se muestra
                        "confirmar monto", //titulo
                        JOptionPane.YES_NO_OPTION, //tipo de ventana
                        JOptionPane.WARNING_MESSAGE // icono
                );

                if (confirmacion == JOptionPane.YES_OPTION) {
                    int id = Integer.parseInt(jTablaRegistros.getValueAt(filaSeleccionada, 0).toString());
                    String nombreCompleto = jTablaRegistros.getValueAt(filaSeleccionada, 1).toString();
                    String apellidoPaterno = jTablaRegistros.getValueAt(filaSeleccionada, 2).toString();
                    String apellidoMaterno = jTablaRegistros.getValueAt(filaSeleccionada, 3).toString();
                    String puesto = jTablaRegistros.getValueAt(filaSeleccionada, 4).toString();

                    Reclutador r = new Reclutador(id, nombreCompleto, apellidoPaterno, apellidoMaterno, puesto, nomina);
                    ReclutadorDAO.getInstance().actualizarNomina(r);
                    cargarReclutadoresEnTabla();
                    JOptionPane.showMessageDialog(null, "Nomina agregada con exito.",
                            "eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Operación cancelada",
                            "operacion cancelada", JOptionPane.INFORMATION_MESSAGE);
                }

                // Si deseas hacer un INSERT a la base de datos, lo puedes usar así:
                // String sql = "INSERT INTO reclutadores (...) VALUES (..., " + nomina + ")";
            } else {
                System.out.println("No se ingresó un valor.");
            }
        } else {
            System.out.println("error");
            JOptionPane.showMessageDialog(null, "Selecciona un empleado para agregar correctamente.",
                    "Error de eliminar", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonAgregarNominaActionPerformed

    private void jButtonCerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarVentanaActionPerformed
        // TODO add your handling code here:
        MenuReclutador Menu = new MenuReclutador();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarVentanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarNomina;
    private javax.swing.JButton jButtonCerrarVentana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1CRUDRH;
    private javax.swing.JLabel jLabelFotoRH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaRegistros;
    // End of variables declaration//GEN-END:variables
}
